[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_MONAD_TESTNET_RPC_URL = "https://testnet-rpc.monad.xyz"
  NEXT_PUBLIC_CHAIN_ID = "41454"
  NEXT_PUBLIC_MWAR_TOKEN_ADDRESS = "0x0000000000000000000000000000000000000000"
  NEXT_PUBLIC_HERO_NFT_ADDRESS = "0x0000000000000000000000000000000000000000"
  NEXT_PUBLIC_GAME_CORE_ADDRESS = "0x0000000000000000000000000000000000000000"
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = "YOUR_PROJECT_ID"
